---
title: "Sample RNASeq Report"
author: "Sameet Mehta"
format: pdf
execute: 
  message: false
  warning: false
  echo: true
editor: visual
params:
  meta_fn: "~/data/reporter_testing/deseq2_2_samples/sample-sheet.txt"
  contrasts_fn: "~/data/reporter_testing/deseq2_2_samples/contrasts.txt"
  count_fn: "~/data/reporter_testing/deseq2_2_samples/gene_count_matrix_fixed.csv"
  op_dir: "~/data/reporter_testing/testing_quartoReport/"
  use_threshold: 0.05
---

## Setup Environment

This is a sample report generated using the `quartoReport` package.

```{r}
#| label: setup

library(quartoReport)
```

## Setup Analysis

```{r}
#| label: setupGlobals

# meta_fn <- "~/data/reporter_testing/deseq2_2_samples/sample-sheet.txt"
# contrasts_fn <- "~/data/reporter_testing/deseq2_2_samples/contrasts.txt"
# count_fn <- "~/data/reporter_testing/deseq2_2_samples/gene_count_matrix_fixed.csv"
# 
# op_dir <- "~/data/reporter_testing/testing_quartoReport/"
# 
# use_threshold <- 0.05
```

### DESeq2 Analysis Setup

```{r}
#| label: setupDESeq2

meta_df <- read_meta_data(params$meta_fn)
count_mat <- read_count_mat(fn = params$count_fn, meta_df = meta_df)
contrasts_df <- get_contrasts(fn = params$contrasts_fn)
```

```{r}
#| label: makeDESEq2

dds <- make_deseq_object(count_mat = count_mat, meta_df = meta_df)
vs_data <- stabilize_count_data(dds)
```

```{r}
#| label: savedds

save_objects(dds, op_dir = params$op_dir)
save_objects(vs_data, op_dir = params$op_dir)
```

```{r}
#| label: results1

res_df <- get_single_result(dds, comp_df = contrasts_df[1, ])
all_plots <- make_all_plots(res_df = res_df, vs_data = vs_data, 
                            thresh = params$use_threshold, op_dir = params$op_dir)
save_results(res_df = res_df, op_dir = params$op_dir, thresh = params$use_threshold)
```

```{r}
#| label: result2
res_df_2 <- get_single_result(dds = dds, comp_df = contrasts_df[2, ])
all_plots_2 <- make_all_plots(res_df = res_df_2, vs_data = vs_data, 
                              thresh = params$use_threshold, op_dir = params$op_dir)
save_results(res_df = res_df_2, op_dir = params$op_dir, thresh = params$use_threshold)
```
